name: Deploy to production

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Deploy to staging']
    types: [completed]
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: actions/checkout@v6.0.2
      - uses: trade-tariff/trade-tariff-tools/.github/actions/terraform-apply@main
        with:
          environment: production
          ref: ${{ github.sha }}
          role-to-assume: arn:aws:iam::382373577178:role/GithubActions-ECS-Deployments-Role
